### ISSUE TITLE
Incorrect value type in Json output format

### ISSUE THREAD

**Issue by cgourdin** [occiware/OCCInterface#9]
Hello,

When getting a resource on my OCCI server with OCCInterface, i have an output like this :
<pre>
<code>
       ...
        "occi.compute.cores" : "1",
        "occi.compute.share" : "0",
        "occi.compute.speed" : "1",
        "occi.compute.memory" : "2",
       ...
</code>
</pre>
I think the json type is incorrect and must be number : 
<pre>
<code>
      ...
      "occi.compute.cores" : 1,
      "occi.compute.share" : 0,
      "occi.compute.speed" : 1.0,
      "occi.compute.memory" : 2.0,
      ...
</code>
</pre>
There is float values (speed and memory), short value (share attribute) and integer value (cores).

**Comment by Romathonat** [comment]
Ok i think I know where the problem is, look [here](https://github.com/occiware/OCCInterface/blob/master/src/components/reactifyJSON/ValueJSON.js#L51). you just have to change the code here 
``` js
<div className="inline">{whiteSpaces+'"'}{value}{'"'+optionalComma+'\n'}</div>

```
The " are always here, even if it is a number. You can make a better template, or put thoses double quotes in variables and check if it is a number, or you can make a simple if else.

**Comment by mdutoo** [comment]
Thank you both of you, nice !
